# fly.toml app configuration file generated for cocomo-2 on 2023-08-20T19:55:37+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cocomo-2"
primary_region = "sin"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.1"

[mounts]
  source="cocomo_2_vol"
  destination="/var/www/html/storage"

[env]
  APP_ENV = "local"
  APP_NAME = "COCOMO FUZZY ESTIMATION"
  DB_CONNECTION = "mysql"
  DB_DATABASE = "cocomo"
  DB_HOST = "aws.connect.psdb.cloud"
  DB_PORT = "3306"
  FILESYSTEM_DRIVER = "public"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  MYSQL_ATTR_SSL_CA = "/etc/ssl/certs/ca-certificates.crt"
  SESSION_DRIVER = "cookie"
  SESSION_SECURE_COOKIE = "true"
  MAIL_MAILER = "smtp"
  MAIL_HOST = "mail.sewamobildanmotorjember.com"
  MAIL_PORT = "465"    
  MAIL_ENCRYPTION = "ssl"  
  MAIL_FROM_NAME = "COCOMO FUZZY ESTIMATION"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

# [deploy]
#   release_command = "php /var/www/html/artisan storage:link"
  # release_command = "php /var/www/html/artisan migrate:fresh --seed --force"
